### ISSUE TITLE
Apps Spec Broken Link

### ISSUE THREAD

**Issue by danaelhe** [digitalocean/openapi#693]
Apps [documentation](https://docs.digitalocean.com/reference/api/api-reference/#tag/Apps) points to a broken link for App specification documentation

```
For documentation on app specifications (AppSpec objects), please refer 
to the [product documentation](https://www.digitalocean.com/docs/app-platform/references/app-specification-reference/).
```

**Comment by andrewsomething** [comment]
Look`https://docs.digitalocean.com/products/app-platform/reference/app-spec/`

**Comment by danaelhe** [comment]
thank you! will do a pr now
