### ISSUE TITLE
Invalid {{contact}}

### ISSUE THREAD

**Issue by mbiesiad** [digitalocean/openapi#779]
Hi,

Please feel free to redirect this issue to proper repo if needed.

Repro steps:
1. Go to https://cloud.digitalocean.com/registrations/email
2. Fill the fields, type as password '123456'
3. See "... {{contact}}"

Result:
"Please try your request again. If the problem persists **{{contact}}**."

Screenshot:
![image](https://user-images.githubusercontent.com/18367606/216692861-a2e1a29f-8e38-419c-93b3-6843c41b84b0.png)

Best wishes,

**Comment by danaelhe** [comment]
Thank you for bringing this to our attention! We have relayed the message to our UI engineers.

**Comment by mbiesiad** [comment]
Hi @danaelhe my pleasure! Thank you for quick action and message. ✨ Have a great day, best wishes
